.PHONY: all clean lua js tinyscheme ecl chicken

all : lua js tinyscheme ecl chicken

lua :
	$(MAKE) -C lua all

js :
	$(MAKE) -C js all

tinyscheme :
	$(MAKE) -C tinyscheme all

ecl :
	$(MAKE) -C ecl all

chicken :
	$(MAKE) -C chicken all

clean :
	$(MAKE) -C lua clean
	$(MAKE) -C js clean
	$(MAKE) -C tinyscheme clean
	$(MAKE) -C ecl clean
	$(MAKE) -C chicken clean

