.PHONY: all clean lua js tinyscheme ecl

all : lua js tinyscheme ecl

lua :
	$(MAKE) -C lua all

js :
	$(MAKE) -C js all

tinyscheme :
	$(MAKE) -C tinyscheme all

ecl :
	$(MAKE) -C ecl all

clean :
	$(MAKE) -C lua clean
	$(MAKE) -C js clean
	$(MAKE) -C tinyscheme clean
	$(MAKE) -C ecl clean

